//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavenWcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HavenWcfService")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/HavenWcfService")]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HasPhoneNumberField;
        
        private long LocalIdField;
        
        private string NameField;
        
        private string PhoneNumberField;
        
        private string PhotoIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HasPhoneNumber
        {
            get
            {
                return this.HasPhoneNumberField;
            }
            set
            {
                this.HasPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LocalId
        {
            get
            {
                return this.LocalIdField;
            }
            set
            {
                this.LocalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoId
        {
            get
            {
                return this.PhotoIdField;
            }
            set
            {
                this.PhotoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactData", Namespace="http://schemas.datacontract.org/2004/07/HavenWcfService")]
    public partial class ContactData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CheckedInField;
        
        private string PhoneNumberField;
        
        private System.DateTime lastCheckInTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckedIn
        {
            get
            {
                return this.CheckedInField;
            }
            set
            {
                this.CheckedInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastCheckInTime
        {
            get
            {
                return this.lastCheckInTimeField;
            }
            set
            {
                this.lastCheckInTimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    HavenWcfService.CompositeType GetDataUsingDataContract(HavenWcfService.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<HavenWcfService.CompositeType> GetDataUsingDataContractAsync(HavenWcfService.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckIn", ReplyAction="http://tempuri.org/IService1/CheckInResponse")]
    System.DateTime CheckIn(System.DateTime DateTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckIn", ReplyAction="http://tempuri.org/IService1/CheckInResponse")]
    System.Threading.Tasks.Task<System.DateTime> CheckInAsync(System.DateTime DateTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAndAddUsersNumber", ReplyAction="http://tempuri.org/IService1/CheckAndAddUsersNumberResponse")]
    bool CheckAndAddUsersNumber(string PhoneNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAndAddUsersNumber", ReplyAction="http://tempuri.org/IService1/CheckAndAddUsersNumberResponse")]
    System.Threading.Tasks.Task<bool> CheckAndAddUsersNumberAsync(string PhoneNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForNewUser", ReplyAction="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForNewUserResponse")]
    HavenWcfService.ContactData[] CheckAndAddUsersPhoneContactsForNewUser(HavenWcfService.Contact[] ContactList);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForNewUser", ReplyAction="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForNewUserResponse")]
    System.Threading.Tasks.Task<HavenWcfService.ContactData[]> CheckAndAddUsersPhoneContactsForNewUserAsync(HavenWcfService.Contact[] ContactList);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForExistingUser", ReplyAction="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForExistingUserResponse" +
        "")]
    HavenWcfService.ContactData[] CheckAndAddUsersPhoneContactsForExistingUser(HavenWcfService.Contact[] ContactList, string PhoneNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForExistingUser", ReplyAction="http://tempuri.org/IService1/CheckAndAddUsersPhoneContactsForExistingUserResponse" +
        "")]
    System.Threading.Tasks.Task<HavenWcfService.ContactData[]> CheckAndAddUsersPhoneContactsForExistingUserAsync(HavenWcfService.Contact[] ContactList, string PhoneNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public HavenWcfService.CompositeType GetDataUsingDataContract(HavenWcfService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.Threading.Tasks.Task<HavenWcfService.CompositeType> GetDataUsingDataContractAsync(HavenWcfService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
    
    public System.DateTime CheckIn(System.DateTime DateTime)
    {
        return base.Channel.CheckIn(DateTime);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> CheckInAsync(System.DateTime DateTime)
    {
        return base.Channel.CheckInAsync(DateTime);
    }
    
    public bool CheckAndAddUsersNumber(string PhoneNumber)
    {
        return base.Channel.CheckAndAddUsersNumber(PhoneNumber);
    }
    
    public System.Threading.Tasks.Task<bool> CheckAndAddUsersNumberAsync(string PhoneNumber)
    {
        return base.Channel.CheckAndAddUsersNumberAsync(PhoneNumber);
    }
    
    public HavenWcfService.ContactData[] CheckAndAddUsersPhoneContactsForNewUser(HavenWcfService.Contact[] ContactList)
    {
        return base.Channel.CheckAndAddUsersPhoneContactsForNewUser(ContactList);
    }
    
    public System.Threading.Tasks.Task<HavenWcfService.ContactData[]> CheckAndAddUsersPhoneContactsForNewUserAsync(HavenWcfService.Contact[] ContactList)
    {
        return base.Channel.CheckAndAddUsersPhoneContactsForNewUserAsync(ContactList);
    }
    
    public HavenWcfService.ContactData[] CheckAndAddUsersPhoneContactsForExistingUser(HavenWcfService.Contact[] ContactList, string PhoneNumber)
    {
        return base.Channel.CheckAndAddUsersPhoneContactsForExistingUser(ContactList, PhoneNumber);
    }
    
    public System.Threading.Tasks.Task<HavenWcfService.ContactData[]> CheckAndAddUsersPhoneContactsForExistingUserAsync(HavenWcfService.Contact[] ContactList, string PhoneNumber)
    {
        return base.Channel.CheckAndAddUsersPhoneContactsForExistingUserAsync(ContactList, PhoneNumber);
    }
}
